{Global english language constants}

const

 _error_read=                '! Error reading ';
 _error_write=               '! Error creating ';
 _disk_full=                 'Disk full';
 _on_the=                    ' on the ';
 _delay=                     'Delay: ';
 _who_has=                   ' who has ';
 _we_have=                   '  We have ';
 _failed=                    ' failed';
 _blocks_of=                 ' blocks of ';
 _bytes=                     ' bytes. ';

 _enc_usage=                 'Usage: Encrypt <filename> <key>';
 _enc_memory=                'Not enough memory for buffer';

 _ins_title='Aurora Polling Network System (APNS) Installation Program';
 _ins_mesg1='Installing from ';
 _ins_mesg2=' to C:\APNS';
 _ins_nocreate='Cannot create directory structure';
 _ins_copyfail=' Copy failed';
 _ins_complete='Installation complete';

 _transfer_aborted=          '! Transfer aborted';
 _session_beginning=         '  Session beginning ';
 _no_handshake=              '! APNS not running on other site';
 _got_handshake=             '  Handshake initiated';
 _no_retrain=                '! Turnaround retrain failed';
 _got_retrain=               '  Turnaround initiated';
 _connected_with=            '  Connected with site: ';
 _files_to_send=             ' files to send';
 _security_violation=        '! Security violation';
 _no_identity_in=            '! Inbound handshaking transfer failed';
 _no_identity_out=           '! Outbound handshaking transfer failed';
 _no_fileinfo_in=            '! Inbound file info transfer failed';
 _no_fileinfo_out=           '! Outbound file info transfer failed';
 _download_of=               '! Download of ';
 _upload_of=                 '! Upload of ';
 _incoming=                  '  Incoming: ';
 _outgoing=                  '  Outgoing: ';
 _successful_session=        '  Successful session';
